<?php

/**
 * @file
 * Drupal Module: Google Analytics Social
 * A submodule add on for googleanalytics module to enable social media tracking
 *
 * @author: Charlie O'Leary <http://drupal.org/user/948772>
 */

/**
 * Implements hook_form_FORMID_alter()
 *
 * Modify the main google analytics settings form to include "Social Tracking" Settings
 */
function google_analytics_social_form_googleanalytics_admin_settings_form_alter(&$form, &$form_state, $form_id) {
  // Insert our settings form into the Vertical tab on the Google Analytics Settings form.
  $form['tracking']['social'] = array(
    '#type' => 'fieldset',
    '#title' => t('Social Tracking'),
  );

  // Create an array for storing facebook tracking settings.
  $form['tracking']['social'] = array(
    '#type' => 'fieldset',
    '#title' => t('Social Tracking'),
  );

  $form['tracking']['social']['google_analytics_social_track_facebook'] = array(
    '#type' => 'checkbox',
    '#title' => t('Track Facebook Actions'),
    '#description' => t('Track actions including Likes, Unlikes and Shares'),
    '#default_value' => variable_get('google_analytics_social_track_facebook', TRUE),
  );

  $form['tracking']['social']['google_analytics_social_track_twitter'] = array(
    '#type' => 'checkbox',
    '#title' => t('Track Twitter Actions'),
    '#description' => t('Track actions including Tweets and Follows'),
    '#default_value' => variable_get('google_analytics_social_track_twitter', TRUE),
  );

  // Add our admin JS.
  drupal_add_js(drupal_get_path('module', 'google_analytics_social') . '/js/google_analytics_social_admin.js');

}

/**
 * Implements hook_page_alter()
 *
 * This is the hook used to insert the original googleanalytics code - so we may as well follow suit
 */
function google_analytics_social_page_alter(&$page) {

  // Do the same checks that are done in google analytics module if we should be tracking
  global $user;

  $id = variable_get('googleanalytics_account', '');

  // Get page status code for visibility filtering.
  $status = drupal_get_http_header('Status');
  $trackable_status_codes = array(
    '403 Forbidden',
    '404 Not Found',
  );
  
  if (!empty($id) && (_googleanalytics_visibility_pages() || in_array($status, $trackable_status_codes)) && _googleanalytics_visibility_user($user)) {
    // If the checks pass
    // Check if the site owner wishes to track facebook actions
    $path = drupal_get_path('module', 'google_analytics_social');
    if (variable_get('google_analytics_social_track_facebook', true)) {
      // Add our Facebook tracking code
      drupal_add_js($path . '/js/google_analytics_social_facebook.js');
    }
    // Or Twitter Actions
    if (variable_get('google_analytics_social_track_twitter', true)) {
      // Initilization of the twitter web intents JS needs to be started before jQuery's $(document).ready()
      drupal_add_js($path . '/js/twitterInit.js');
      // Add our twitter tracking code
      drupal_add_js($path . '/js/google_analytics_social_twitter.js');
    }
  }
}